export interface Project {
  _id: number;
  description: string;
  name: string;
  main_concrete_type: string;
  main_concrete_type_uncertainty: string;
  receiver_country: string;
  receiver_city: string;
  receiver_coordinates: string;
  location_uncertainty: string;
  distance_km: number;
  distance_smaller: string;
  distance_uncertainty: number;
  start_date_year: number;
  date_uncertainty: string;
  component_age: number;
  age_smaller: string;
  age_uncertainty: string;
  quantity_reclaimed: string;
  quantity_reclaimed_unit: string;
  donor_nb_floor: string;
  donor_nb_floor_smaller: string;
  donor_use: string;
  donor_element_type: string;
  receiver_nb_floor: number;
  receiver_nb_floor_smaller: string;
  receiver_nb_floor_uncertainty: string;
  receiver_use: string;
  receiver_element_type: string;
  reference: string;
  impact_design_alternative: string;
  impact_difference: string;
  impact_unit: string;
  impact_source: string;
  cost_design_alternative: string;
  cost_difference_min_percent: string;
  cost_difference_max_percent: string;
  cost_source: string;
  images: string;
  images_credits: string;
}

export type ProjectKey = keyof Project;