name: Quality Checks

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=16.0.0 < 23.0.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run ESLint
        run: npm run lint

      - name: Run Stylelint
        run: npx stylelint "**/*.{css,scss}"

      - name: Check formatting
        run: npm run format -- --check

      - name: Type check
        run: npm run convert && npm run type-check

